// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmkOj_zmQiBMG_tPFpQ0KYRIbDGZ660dY',
    appId: '1:845575425090:web:19b0edff53a5f1285eb1db',
    messagingSenderId: '845575425090',
    projectId: 'bismillah-web',
    authDomain: 'bismillah-web.firebaseapp.com',
    storageBucket: 'bismillah-web.appspot.com',
    measurementId: 'G-L83EKDPB0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8QO6iIfHBIxQjY75tF2KDwlM2DtPLuQ',
    appId: '1:845575425090:android:dfeefd626d656d0f5eb1db',
    messagingSenderId: '845575425090',
    projectId: 'bismillah-web',
    storageBucket: 'bismillah-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLNDg0e5xJJtgScShkpkyJFQqf3K0dSA',
    appId: '1:845575425090:ios:a3378c6c612849385eb1db',
    messagingSenderId: '845575425090',
    projectId: 'bismillah-web',
    storageBucket: 'bismillah-web.appspot.com',
    iosBundleId: 'com.example.dashboardWebproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmkOj_zmQiBMG_tPFpQ0KYRIbDGZ660dY',
    appId: '1:845575425090:web:1718f0b29fd1f5705eb1db',
    messagingSenderId: '845575425090',
    projectId: 'bismillah-web',
    authDomain: 'bismillah-web.firebaseapp.com',
    storageBucket: 'bismillah-web.appspot.com',
    measurementId: 'G-1XE2C9DHSF',
  );

}